
describe('Uspesan login', function() {
    it('Validni kredencijali', function() {
      cy.visit('https://gallery-app.vivifyideas.com/')
      cy.contains('Login').click()
      cy.get('#email').type('sale.spirit@gmail.com')
      cy.get('#password').type('t3stiranje')
      cy.contains('Submit').click()
      cy.wait(5000)
      cy.contains('Logout').should('be.visible') 
      cy.contains('My Galleries').should('be.visible') 
      cy.contains('Create Gallery').should('be.visible') 
      cy.url().should('eq', 'https://gallery-app.vivifyideas.com/')
    })
})
describe('Neuspesan login', function() {
    it('Prazan email', function() {
      cy.visit('https://gallery-app.vivifyideas.com/')
      cy.contains('Login').click()
      cy.get('#password').type('t3stiranje')
      cy.contains('Submit').click()
      cy.wait(5000)
      cy.url().should('eq', 'https://gallery-app.vivifyideas.com/')
      cy.contains('Logout').should('be.visible') 
      cy.contains('My Galleries').should('be.visible') 
      cy.contains('Create Gallery').should('be.visible') 
    })
})
describe('Nespesan login', function() {
    it('Prazan password', function() {
      cy.visit('https://gallery-app.vivifyideas.com/')
      cy.contains('Login').click()
      cy.get('#email').type('sale.spirit@gmail.com')
      cy.contains('Submit').click()
      cy.wait(5000)
      cy.url().should('eq', 'https://gallery-app.vivifyideas.com/')
      cy.contains('Logout').should('be.visible') 
      cy.contains('My Galleries').should('be.visible') 
      cy.contains('Create Gallery').should('be.visible') 
    })
})
describe('Nespesan login', function() {
    it('Prazani i email i password', function() {
      cy.visit('https://gallery-app.vivifyideas.com/')
      cy.contains('Login').click()
      cy.contains('Submit').click()
      cy.wait(5000)
      cy.url().should('eq', 'https://gallery-app.vivifyideas.com/')
      cy.contains('Logout').should('be.visible') 
      cy.contains('My Galleries').should('be.visible') 
      cy.contains('Create Gallery').should('be.visible') 
    })
})
describe('Neuspesan login', function() {
    it('Invalidni kredencijali', function() {
      cy.visit('https://gallery-app.vivifyideas.com/')
      cy.contains('Login').click()
      cy.get('#email').type('menenekoovdesprda@gmail.com')
      cy.get('#password').type('maj3333ste')
      cy.contains('Submit').click()
      cy.wait(5000)
      cy.url().should('eq', 'https://gallery-app.vivifyideas.com/')
      cy.contains('Logout').should('be.visible') 
      cy.contains('My Galleries').should('be.visible') 
      cy.contains('Create Gallery').should('be.visible') 
    })
})
