describe('Login testiranje', function() {
    it('Validni kredencijali', function() {
      cy.visit('https://gallery-app.vivifyideas.com/')
      cy.get('.nav-link').contains('Login').click()
      cy.get('#email').type('sale.spirit@gmail.com')
      cy.get('#password').type('t3stiranje')
      cy.contains('Submit').click()
      cy.wait(5000)
      cy.get('.nav-link').contains('Logout').should('be.visible') 
      cy.get('.nav-link').contains('My Galleries').should('be.visible') 
      cy.get('.nav-link').contains('Create Gallery').should('be.visible') 
      cy.url().should('eq', 'https://gallery-app.vivifyideas.com/')
    })
    it('Prazan email', function() {
        cy.visit('https://gallery-app.vivifyideas.com/')
        cy.get('.nav-link').contains('Login').click()
        cy.get('#password').type('t3stiranje')
        cy.contains('Submit').click()
        cy.wait(5000)
        cy.url().should('eq', 'https://gallery-app.vivifyideas.com/')
        cy.get('.nav-link').contains('Logout').should('be.visible') 
        cy.get('.nav-link').contains('My Galleries').should('be.visible') 
        cy.get('.nav-link').contains('Create Gallery').should('be.visible') 
    })
      it('Prazan password', function() {
        cy.visit('https://gallery-app.vivifyideas.com/')
        cy.get('.nav-link').contains('Login').click()
        cy.get('#email').type('sale.spirit@gmail.com')
        cy.contains('Submit').click()
        cy.wait(5000)
        cy.url().should('eq', 'https://gallery-app.vivifyideas.com/')
        cy.get('.nav-link').contains('Logout').should('be.visible') 
        cy.get('.nav-link').contains('My Galleries').should('be.visible') 
        cy.get('.nav-link').contains('Create Gallery').should('be.visible') 
    })
      it('Prazani i email i password', function() {
        cy.visit('https://gallery-app.vivifyideas.com/')
        cy.get('.nav-link').contains('Login').click()
        cy.contains('Submit').click()
        cy.wait(5000)
        cy.url().should('eq', 'https://gallery-app.vivifyideas.com/')
        cy.get('.nav-link').contains('Logout').should('be.visible') 
        cy.get('.nav-link').contains('My Galleries').should('be.visible') 
        cy.get('.nav-link').contains('Create Gallery').should('be.visible') 
    })
      it('Invalidni kredencijali', function() {
        cy.visit('https://gallery-app.vivifyideas.com/')
        cy.get('.nav-link').contains('Login').click()
        cy.get('#email').type('menenekoovdesprda@gmail.com')
        cy.get('#password').type('maj3333ste')
        cy.contains('Submit').click()
        cy.wait(5000)
        cy.url().should('eq', 'https://gallery-app.vivifyideas.com/')
        cy.get('.nav-link').contains('Logout').should('be.visible') 
        cy.get('.nav-link').contains('My Galleries').should('be.visible') 
        cy.get('.nav-link').contains('Create Gallery').should('be.visible') 
    })
})




